name: AnapolisCore
version: '${project.version}'
main: com.rune.anapoliscore.Main
api-version: 1.16
authors: [ Rune ]
depend: [Vault]
description:
  Core plugin Voor Anapolis (Alle rechten van deze plugin gaan naar Rune (DC: Rune#0734) )
commands:
  bank:
    usage: /<command>
    description: maak van een blok een bank